
service: project-backend

frameworkVersion: '2'

# serverless 에 붙이기
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-2

functions:
  project_crawler:
    handler: services.project_crawler.main
    events:
      - http:
          path: /project_crawler
          method: get
          cors: true   

